repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.json]
        additional_dependencies: [markdownlint-cli2]
        exclude: |
          (?x)^(
            \.github/.*|
            \.devcontainer/.*
          )$