repos:
  # General file checks (safe and useful)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.json]
        additional_dependencies: [markdownlint-cli2]
        exclude: |
          (?x)^(
            \.github/.*|
            \.devcontainer/.*
          )$

  # Python code quality (optional - can be enabled later)
  # - repo: https://github.com/psf/black
  #   rev: 24.10.0
  #   hooks:
  #     - id: black
  #       language_version: python3
  #       args: [--line-length=88]
  #       exclude: |
  #         (?x)^(
  #           \.venv/.*|
  #           venv/.*|
  #           backend/venv/.*|
  #           __pycache__/.*|
  #           \.pytest_cache/.*
  #         )$

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       args: [--profile=black, --line-length=88]
  #       exclude: |
  #         (?x)^(
  #           \.venv/.*|
  #           venv/.*|
  #           backend/venv/.*|
  #           __pycache__/.*|
  #           \.pytest_cache/.*
  #         )$

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=88, --extend-ignore=E203,W503,E501,E402,E722,F821,F841]
  #       exclude: |
  #         (?x)^(
  #           \.venv/.*|
  #           venv/.*|
  #           backend/venv/.*|
  #           __pycache__/.*|
  #           \.pytest_cache/.*|
  #           backend/tests/examples/.*
  #         )$

  # JavaScript/Node.js quality (optional - can be enabled later)
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.15.0
  #   hooks:
  #     - id: eslint
  #       files: \.(js|jsx)$
  #       additional_dependencies:
  #         - eslint@^8.0.0
  #         - eslint-plugin-react@^7.33.0
  #         - eslint-plugin-react-hooks@^4.6.0
  #         - eslint-plugin-jsx-a11y@^6.8.0
  #       args: [--fix]

  # Security checks (optional - can be enabled later)
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  #       args: [--baseline, .secrets.baseline]
  #       exclude: |
  #         (?x)^(
  #           package-lock\.json$|
  #           yarn\.lock$|
  #           \.venv/.*|
  #           venv/.*|
  #           backend/venv/.*|
  #           node_modules/.*
  #         )$
