name: API Tests
# Last Updated: October 2025

permissions:
  contents: read

concurrency:
  group: api-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - "tests/api/**"
      - ".github/workflows/api-tests.yml"
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  newman:
    name: Run Postman/Newman Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testbook
          POSTGRES_PASSWORD: testbook
          POSTGRES_DB: testbook_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Start backend server
        working-directory: ./backend
        env:
          TESTING: true
          SECRET_KEY: test-secret-key-for-ci
          DATABASE_URL: postgresql+psycopg://testbook:testbook@localhost:5432/testbook_test
        run: |
          python seed.py
          uvicorn main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          sleep 10

      - name: Wait for backend
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8000/api/health; do sleep 1; done' || (cat backend/server.log && exit 1)

      - name: Run Postman collection
        run: |
          newman run tests/api/Testbook.postman_collection.json \
            --environment tests/api/Testbook.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman-report.html \
            --bail

      - name: Upload Newman report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
          retention-days: 7

  python-requests:
    name: Run Python API Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testbook
          POSTGRES_PASSWORD: testbook
          POSTGRES_DB: testbook_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install requests

      - name: Start backend server
        working-directory: ./backend
        env:
          TESTING: true
          SECRET_KEY: test-secret-key-for-ci
          DATABASE_URL: postgresql+psycopg://testbook:testbook@localhost:5432/testbook_test
        run: |
          python seed.py
          uvicorn main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          sleep 10

      - name: Wait for backend
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8000/api/health; do sleep 1; done' || (cat backend/server.log && exit 1)

      - name: Run Python API examples
        run: |
          python tests/api/python_api_examples.py
