name: Frontend Tests
# Last Updated: October 2025

permissions:
  contents: read

concurrency:
  group: frontend-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-tests.yml"
  pull_request:
  workflow_dispatch:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run linting
        working-directory: ./frontend
        run: |
          npm run lint || true

      - name: Run unit tests
        working-directory: ./frontend
        env:
          FORCE_COLOR: 0
        run: npm test -- --run

      - name: Run accessibility tests
        working-directory: ./frontend
        env:
          FORCE_COLOR: 0
        run: npm run test:a11y

      - name: Generate coverage report
        working-directory: ./frontend
        env:
          FORCE_COLOR: 0
        run: npm run test:coverage -- --run

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-node${{ matrix.node-version }}
          path: frontend/coverage/
          retention-days: 7

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-node${{ matrix.node-version }}
          path: frontend/dist/
          retention-days: 7
